/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import { CacheFirst, StaleWhileRevalidate } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";
import { CacheableResponsePlugin } from "workbox-cacheable-response";

declare let self: ServiceWorkerGlobalScope;

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Tile provider patterns for caching
const TILE_CACHE_NAME = "map-tiles-v1";
const TILE_CACHE_MAX_AGE_SECONDS = 7 * 24 * 60 * 60; // 1 week
const TILE_CACHE_MAX_ENTRIES = 500;

// Tile URL patterns to cache
const tilePatterns = [
  // OpenStreetMap tiles
  /tile\.openstreetmap\.org/,
  // Stadia Maps tiles
  /tiles\.stadiamaps\.com/,
  // MapTiler tiles
  /api\.maptiler\.com/,
  // Mapbox tiles
  /api\.mapbox\.com/,
];

// Cache map tiles with a stale-while-revalidate strategy
tilePatterns.forEach((pattern) => {
  registerRoute(
    ({ url }) => pattern.test(url.href),
    new StaleWhileRevalidate({
      cacheName: TILE_CACHE_NAME,
      plugins: [
        new CacheableResponsePlugin({
          statuses: [0, 200],
        }),
        new ExpirationPlugin({
          maxEntries: TILE_CACHE_MAX_ENTRIES,
          maxAgeSeconds: TILE_CACHE_MAX_AGE_SECONDS,
        }),
      ],
    })
  );
});

// Cache images (marker icons, etc.) with cache-first strategy
registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst({
    cacheName: "images-v1",
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Handle navigation requests - for PWA app shell
registerRoute(
  new NavigationRoute(
    new StaleWhileRevalidate({
      cacheName: "pages-v1",
      plugins: [
        new CacheableResponsePlugin({
          statuses: [0, 200],
        }),
      ],
    }),
    {
      // Don't cache these paths
      denylist: [/\/api\//],
    }
  )
);

// Listen for skip waiting message
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Notify clients of updates
self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      // Claim all clients immediately
      await self.clients.claim();
    })()
  );
});
